// Generated by https://quicktype.io

export interface IBuscarDni {
    dni:             string;
    nombres:         string;
    apellidoPaterno: string;
    apellidoMaterno: string;
    nombreCompleto:  string;
}
