// Generated by https://quicktype.io

export interface IUsuariosListar {
    numeroDocumento:   string;
    email:          string;
    isActive:       boolean;
    roles:          string[];
    nombreEmpleado: null | string;
}
